# Generated by Django 5.0.1 on 2024-02-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('current_job_place', models.CharField(default='', max_length=255)),
                ('designation', models.CharField(default='', max_length=255)),
                ('year_of_experience', models.CharField(default='', max_length=10)),
                ('qualification', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('website_link', models.URLField(default='')),
                ('language', models.CharField(default='', max_length=255)),
                ('career_objective', models.TextField(default='')),
                ('facebook', models.URLField(default='')),
                ('twitter', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('pinterest', models.URLField(default='')),
                ('dribbble', models.URLField(default='')),
                ('behance', models.URLField(default='')),
                ('father_name', models.CharField(default='', max_length=255)),
                ('mother_name', models.CharField(default='', max_length=255)),
                ('national_id', models.CharField(default='', max_length=20)),
                ('present_address', models.CharField(default='', max_length=255)),
                ('permanent_address', models.CharField(default='', max_length=255)),
                ('marital_status', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default='', max_length=20)),
                ('religion', models.CharField(default='', max_length=255)),
                ('blood_group', models.CharField(default='', max_length=5)),
                ('height', models.CharField(default='', max_length=10)),
                ('weight', models.CharField(default='', max_length=10)),
                ('education_level', models.CharField(default='', max_length=255)),
                ('major', models.CharField(default='', max_length=255)),
                ('institute', models.CharField(default='', max_length=255)),
                ('result_gpa', models.CharField(default='', max_length=10)),
                ('starting_period_education', models.DateField(default='2000-01-01')),
                ('ending_period_education', models.DateField(default='2000-01-01')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('designation_employment', models.CharField(default='', max_length=255)),
                ('starting_period_employment', models.DateField(default='2000-01-01')),
                ('ending_period_employment', models.DateField(default='2000-01-01')),
                ('responsibility', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
