# Generated by Django 5.0.1 on 2024-02-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_remove_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='participant_profile_images/'),
        ),
    ]
