# Generated by Django 5.0.1 on 2024-02-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_profile_images/'),
        ),
    ]
