# Generated by Django 5.0.1 on 2024-06-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('free_regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(default='2 hours', max_length=255)),
                ('lesson_set', models.CharField(default='30 lessons', max_length=255)),
                ('about_course', models.TextField()),
                ('start_date', models.DateField()),
                ('language', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('course_tags', models.TextField()),
                ('video_url', models.URLField()),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('lesson_1', models.URLField(blank=True, null=True)),
                ('lesson_2', models.URLField(blank=True, null=True)),
                ('lesson_3', models.URLField(blank=True, null=True)),
                ('lesson_4', models.URLField(blank=True, null=True)),
                ('lesson_5', models.URLField(blank=True, null=True)),
                ('lesson_6', models.URLField(blank=True, null=True)),
                ('lesson_7', models.URLField(blank=True, null=True)),
                ('lesson_8', models.URLField(blank=True, null=True)),
                ('lesson_9', models.URLField(blank=True, null=True)),
                ('lesson_10', models.URLField(blank=True, null=True)),
                ('lesson_11', models.URLField(blank=True, null=True)),
                ('lesson_12', models.URLField(blank=True, null=True)),
                ('lesson_13', models.URLField(blank=True, null=True)),
                ('lesson_14', models.URLField(blank=True, null=True)),
                ('lesson_15', models.URLField(blank=True, null=True)),
                ('lesson_16', models.URLField(blank=True, null=True)),
                ('lesson_17', models.URLField(blank=True, null=True)),
                ('lesson_18', models.URLField(blank=True, null=True)),
                ('lesson_19', models.URLField(blank=True, null=True)),
                ('lesson_20', models.URLField(blank=True, null=True)),
                ('lesson_21', models.URLField(blank=True, null=True)),
                ('lesson_22', models.URLField(blank=True, null=True)),
                ('lesson_23', models.URLField(blank=True, null=True)),
                ('lesson_24', models.URLField(blank=True, null=True)),
                ('lesson_25', models.URLField(blank=True, null=True)),
                ('lesson_26', models.URLField(blank=True, null=True)),
                ('lesson_27', models.URLField(blank=True, null=True)),
                ('lesson_28', models.URLField(blank=True, null=True)),
                ('lesson_29', models.URLField(blank=True, null=True)),
                ('lesson_30', models.URLField(blank=True, null=True)),
                ('course_material_1', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_material_2', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_material_3', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_material_4', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('course_material_5', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('csv_file', models.FileField(default=True, upload_to='csv_files/')),
                ('description', models.TextField(blank=True)),
                ('users', models.ManyToManyField(related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
