# Generated by Django 5.0.1 on 2024-02-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_certificatetemplate_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursebuildertopic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursebuildertopic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_image',
            field=models.ImageField(default=True, upload_to='certificate_templates/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
        migrations.DeleteModel(
            name='CourseBuilderTopic',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
