# Generated by Django 5.0.1 on 2024-06-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrolledcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='enrolled_at',
            new_name='enrolled_date',
        ),
        migrations.AlterUniqueTogether(
            name='enrolledcourse',
            unique_together=set(),
        ),
    ]
