# Generated by Django 5.0.1 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_material_course_lesson_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_material',
            new_name='course_material_1',
        ),
        migrations.AddField(
            model_name='course',
            name='course_material_2',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_material_3',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_material_4',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_material_5',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
    ]
