# Generated by Django 5.0.1 on 2024-02-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_course_material_course_course_material_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='2 hours', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_set',
            field=models.CharField(default='30 lessons', max_length=255),
        ),
    ]
