# Generated by Django 5.0.1 on 2024-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_question_answer_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='csv_file',
            field=models.FileField(default=True, upload_to='csv_files/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
