# Generated by Django 5.0.1 on 2024-02-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_instructor_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
    ]
